---
- hosts:
    - production
  user: root
  tasks:
    - name: deploy
      git:
        repo: git@bitbucket.org:DrPheltRight/lukemorton.co.uk.git
        dest: /var/www/lukemorton.co.uk
        version: develop
      notify: apache-restart

    - name: Update composer packages
      command: /usr/local/bin/composer install -d /var/www/lukemorton.co.uk

    - name: Create application log and cache directories
      file:
        dest: /var/www/lukemorton.co.uk/${item}
        state: directory
        owner: www-data
        group: www-data
        mode: 0755
      with_items:
        - poems/logs/
        - poems/cache/

  handlers:
    - include: roles/apache/handlers/main.yml
