---
- hosts:
    - production
  user: root
  roles:
    - php
    - apache
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: install git
      apt: pkg=git state=present

    - name: create luke's .ssh directory
      file:
        dest: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: 0700

    - name: Copy ssh deploy private key
      copy:
        src: files/bitbucket
        dest: /root/.ssh/bitbucket
        mode: 0600
        owner: root
        group: root

    - name: Copy ssh config
      copy:
        src: files/deploy_ssh_config
        dest: /root/.ssh/config
        owner: root
        group: root
        mode: 0600
