---
- name: Apache | Install Apache-Prefork
  apt: pkg=apache2-mpm-prefork state=installed

- name: Apache | Copy vhost
  template: 
    src: lukemorton.vh
    dest: /etc/apache2/sites-available/lukemorton.co.uk
  notify: apache-restart

- name: Apache | Enable vhost
  file:
    src: /etc/apache2/sites-available/lukemorton.co.uk
    dest: /etc/apache2/sites-enabled/lukemorton.co.uk
    state: link
  notify: apache-restart

- name: Apache | Enable htaccess rewrites
  file:
    src: /etc/apache2/mods-available/rewrite.load
    dest: /etc/apache2/mods-enabled/rewrite.load
    state: link
  notify: apache-restart

- name: Apache | Remove default index file from default docroot
  file: path=/var/www/index.html state=absent

- name: Apache | Disable default vhost
  file:
    dest: /etc/apache2/sites-enabled/000-default
    state: absent
  notify: apache-restart

- name: Apache | Insure deamon is running correctly
  service: name=apache2 state=started
